# Generated by Django 5.2.6 on 2026-07-24 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 0.5 to 5.0', max_digits=2, null=True)),
                ('occasion', models.CharField(choices=[('Casual', 'Casual'), ('Work', 'Work'), ('Evening', 'Evening'), ('Formal', 'Formal'), ('Special', 'Special Occasion')], default='Casual', max_length=20)),
                ('sprays', models.PositiveIntegerField(default=3)),
                ('sillage_rating', models.PositiveSmallIntegerField(blank=True, help_text='Projection score from 1 (Intimate) to 5 (Enormous)', null=True)),
                ('longevity_hours', models.PositiveSmallIntegerField(blank=True, help_text='Duration of skin wear in hours', null=True)),
                ('review_text', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False, help_text='Highlight as a standout wear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scent_logs', to='catalog.fragrance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-wear_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('scent_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='diary.scentlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scentlog',
            index=models.Index(fields=['user', '-wear_date'], name='diary_scent_user_id_d40540_idx'),
        ),
        migrations.AddIndex(
            model_name='scentlog',
            index=models.Index(fields=['fragrance', '-created_at'], name='diary_scent_fragran_0a373a_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'scent_log'), name='unique_like'),
        ),
    ]
