# Generated by Django 5.2.6 on 2026-07-24 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_fragrance', models.ForeignKey(blank=True, help_text='Signature fragrance preference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by_profiles', to='catalog.fragrance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow')],
            },
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(choices=[('Owned', 'Owned'), ('Wishlist', 'Wishlist'), ('Tried', 'Tried'), ('Want to Try', 'Want to Try')], default='Owned', max_length=20)),
                ('personal_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5', null=True)),
                ('bottle_size_ml', models.PositiveIntegerField(default=100, help_text='Bottle size in ML')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_entries', to='catalog.fragrance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'fragrance'), name='unique_wardrobe_entry')],
            },
        ),
    ]
