# Generated by Django 5.2.6 on 2026-07-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260731_1845'),
    ]

    operations = [
    ]
