# Generated by Django 5.2.6 on 2026-07-31 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260731_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='bottle_size_ml',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Bottle size in ML', null=True),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='personal_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
