# Generated by Django 6.1 on 2026-08-09 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wardrobeitem_bottle_size_ml_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_email_on_profile', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('English', 'English'), ('Armenian', 'Armenian'), ('Russian', 'Russian')], default='English', max_length=20)),
                ('remember_me_default', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('Public', 'Public'), ('Followers Only', 'Followers Only'), ('Private', 'Private')], default='Public', max_length=20)),
                ('show_wardrobe_publicly', models.BooleanField(default=True)),
                ('show_follower_list', models.BooleanField(default=True)),
                ('allow_follow_requests', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('notify_new_follower', models.BooleanField(default=True)),
                ('notify_comments_likes', models.BooleanField(default=True)),
                ('weekly_digest_email', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Auto', 'Auto')], default='Auto', max_length=10)),
                ('compact_wardrobe_view', models.BooleanField(default=False)),
                ('show_ratings_on_cards', models.BooleanField(default=True)),
                ('default_shelf', models.CharField(choices=[('Owned', 'Owned'), ('Wishlist', 'Wishlist'), ('Tried', 'Tried'), ('Want to Try', 'Want to Try')], default='Owned', max_length=20)),
                ('bottle_size_unit', models.CharField(choices=[('ML', 'Milliliters'), ('OZ', 'Fluid Ounces')], default='ML', max_length=5)),
                ('auto_add_viewed_to_wishlist', models.BooleanField(default=False)),
                ('show_wardrobe_value_estimate', models.BooleanField(default=False)),
                ('allow_tagging', models.BooleanField(default=True)),
                ('show_activity_on_profile', models.BooleanField(default=True)),
                ('discoverable_in_search', models.BooleanField(default=True)),
                ('allow_data_export', models.BooleanField(default=True)),
                ('include_wardrobe_in_export', models.BooleanField(default=True)),
                ('diary_retention', models.CharField(choices=[('Never', 'Never'), ('90', '90 Days'), ('180', '180 Days'), ('365', '365 Days')], default='Never', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
