# Generated by Django 6.0.7 on 2026-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accent_color',
            field=models.CharField(choices=[('Brass', 'Brass'), ('Navy', 'Navy'), ('Tobacco', 'Tobacco')], default='Brass', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='allow_direct_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='beta_features_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_sort_order',
            field=models.CharField(choices=[('Recently Added', 'Recently Added'), ('Name', 'Name'), ('House', 'House'), ('Rating', 'Rating')], default='Recently Added', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='export_format',
            field=models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON')], default='CSV', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='hide_from_search_engines',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='login_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='low_stock_threshold_ml',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_new_release_in_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_price_drops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='require_password_for_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='session_device_list_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='session_timeout_minutes',
            field=models.CharField(choices=[('15', '15 Minutes'), ('30', '30 Minutes'), ('60', '60 Minutes'), ('Never', 'Never')], default='60', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_empty_bottle_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_last_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_wishlist_publicly',
            field=models.BooleanField(default=True),
        ),
    ]
