# Generated by Django 5.2.6 on 2026-07-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=10)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('source_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrances', to='catalog.house')),
                ('base_notes', models.ManyToManyField(blank=True, related_name='base_notes', to='catalog.note')),
                ('heart_notes', models.ManyToManyField(blank=True, related_name='heart_notes', to='catalog.note')),
                ('top_notes', models.ManyToManyField(blank=True, related_name='top_notes', to='catalog.note')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'house'], name='catalog_fra_name_28b8b3_idx')],
            },
        ),
    ]
