# Generated by Django 5.2.6 on 2026-08-11 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fragrance',
            name='concentration',
            field=models.CharField(blank=True, choices=[('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('Parfum', 'Parfum / Extrait'), ('EDC', 'Eau de Cologne'), ('Mist', 'Body Mist')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fragrance',
            name='family',
            field=models.CharField(blank=True, choices=[('Woody', 'Woody'), ('Floral', 'Floral'), ('Oriental', 'Oriental'), ('Fresh', 'Fresh'), ('Gourmand', 'Gourmand'), ('Citrus', 'Citrus'), ('Aquatic', 'Aquatic'), ('Chypre', 'Chypre'), ('Fougere', 'Fougère'), ('Leather', 'Leather'), ('Aromatic', 'Aromatic'), ('Green', 'Green')], db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FragranceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.fragrance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fragrance', '-created_at'], name='catalog_fra_fragran_309093_idx'), models.Index(fields=['fragrance', '-helpful_count'], name='catalog_fra_fragran_6070dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('fragrance', 'user'), name='unique_fragrance_review')],
            },
        ),
    ]
