# Generated by Django 5.2.6 on 2026-08-21 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_fragrance_concentration_fragrance_family_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragrance',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='fragrance',
            name='family',
        ),
        migrations.CreateModel(
            name='FragranceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('time_of_day', 'Best Time of Day'), ('season', 'Best Season'), ('longevity', 'Longevity'), ('projection', 'Projection')], max_length=20)),
                ('choice', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='catalog.fragrance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FragranceReview',
        ),
        migrations.AddIndex(
            model_name='fragrancevote',
            index=models.Index(fields=['fragrance', 'category'], name='catalog_fra_fragran_295a00_idx'),
        ),
        migrations.AddConstraint(
            model_name='fragrancevote',
            constraint=models.UniqueConstraint(fields=('user', 'fragrance', 'category'), name='unique_user_fragrance_category_vote'),
        ),
    ]
