# Generated by Django 5.2.6 on 2026-08-22 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_fragrance_concentration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fragrance composition name', max_length=255)),
                ('house_name', models.CharField(help_text='Perfume house or designer brand', max_length=255)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=10)),
                ('release_year', models.IntegerField(blank=True, help_text='Release year if known', null=True)),
                ('top_notes', models.CharField(blank=True, help_text='Top / Opening notes (comma-separated)', max_length=500)),
                ('heart_notes', models.CharField(blank=True, help_text='Heart / Middle notes (comma-separated)', max_length=500)),
                ('base_notes', models.CharField(blank=True, help_text='Base / Drydown notes (comma-separated)', max_length=500)),
                ('reference_url', models.URLField(blank=True, help_text='Official house link or reference listing', max_length=500)),
                ('notes_or_comments', models.TextField(blank=True, help_text='Additional olfactory or context notes', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Added'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by curators/staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fragrance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='catalog_fra_status_0171fc_idx')],
            },
        ),
    ]
