# Generated by Django 5.2.6 on 2026-08-27 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fragrancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragrancerequest',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='fragrancerequest',
            name='base_notes',
        ),
        migrations.RemoveField(
            model_name='fragrancerequest',
            name='heart_notes',
        ),
        migrations.RemoveField(
            model_name='fragrancerequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fragrancerequest',
            name='notes_or_comments',
        ),
        migrations.RemoveField(
            model_name='fragrancerequest',
            name='top_notes',
        ),
        migrations.AddField(
            model_name='fragrancerequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal note from the team'),
        ),
        migrations.AddField(
            model_name='fragrancerequest',
            name='fragrance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fragrancerequest',
            name='notes_description',
            field=models.TextField(blank=True, help_text='Any known notes or additional details about the fragrance'),
        ),
        migrations.AddField(
            model_name='fragrancerequest',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fragrancerequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fragrancerequest',
            name='house_name',
            field=models.CharField(blank=True, help_text='Brand or design house name', max_length=255),
        ),
        migrations.AlterField(
            model_name='fragrancerequest',
            name='reference_url',
            field=models.URLField(blank=True, help_text='Link to Fragrantica, Parfumo, or official page', max_length=500),
        ),
        migrations.AlterField(
            model_name='fragrancerequest',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fragrancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Added', 'Added'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fragrancerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
