# Generated by Django 5.2.6 on 2026-09-05 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_fragrancerequest_admin_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceWaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wafts', to='catalog.fragrance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fragrance', '-created_at'], name='catalog_fra_fragran_1477c8_idx'), models.Index(fields=['user', '-created_at'], name='catalog_fra_user_id_09cfc2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'fragrance'), name='unique_user_fragrance_waft')],
            },
        ),
    ]
